include:
  - docker/compose.databases.yml
  - docker/compose.messaging.yml
  - docker/compose.observability.yml
  - docker/compose.apps.yml

networks:
  app-network:
    name: korp-app-network
    driver: bridge
  db-network:
    name: korp-db-network
    driver: bridge
  messaging-network:
    name: korp-messaging-network
    driver: bridge
  observability-network:
    name: korp-observability-network
    driver: bridge
