services:
  postgres:
    image: postgres:16-alpine
    container_name: estoque-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: estoquedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d estoquedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: faturamento-db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourPassword123!' -C -Q 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - db-network

volumes:
  postgres_data:
  sqlserver_data:
